Cleanup disks service
kubernetes-sigs/cluster-api-provider-azure pull request #1013
Opened 2020-10-28 18:42 UTC by shysank

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Cleanup disks service
- Make `Client` interface private ( the methods are still exported to generate mocks)
- Move `DiskScope` and `Service` struct to `disks.go`
- `NewService()` -> `New()` 
- Remove redundant initialization code in `disks_test.go`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1001 (Partially)

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Cleanup disks service
```

2020-10-28 20:22 UTC, CecileRobertMichon commented
/ok-to-test

2020-10-28 20:34 UTC, nader-ziada commented
I like the approach 👍

2020-10-28 22:54 UTC, shysank commented
API Diff
```
sigs.k8s.io/cluster-api-provider-azure/cloud/services/disks/mock_disks
  Incompatible changes:
  - MockClient: removed
  - MockClientMockRecorder: removed
  - NewMockClient: removed
  Compatible changes:
  - Mockclient: added
  - MockclientMockRecorder: added
  - NewMockclient: added
sigs.k8s.io/cluster-api-provider-azure/cloud/services/disks
  Incompatible changes:
  - AzureClient: removed
  - Client: removed
  - NewClient: removed
  - NewService: removed
  - Service.Client: removed
  Compatible changes:
  - New: added
```

2020-10-29 13:59 UTC, nader-ziada commented
@devigned what do you think?

2020-10-29 14:32 UTC, devigned requested changes
It's beautiful!

I left one super small nit. Thank you and great work!

2020-10-29 14:32 UTC, devigned commented on cloud/services/disks/client.go
> +var _ client = &azureClient{}
```suggestion
var _ client = (*azureClient)(nil)
```

^ no allocation needed

2020-10-29 18:13 UTC, shysank commented on cloud/services/disks/client.go
> +var _ client = &azureClient{}
Fixed it, Thanks!

2020-10-29 20:12 UTC, CecileRobertMichon approved these changes
lgtm

2020-10-29 20:19 UTC, devigned approved these changes
/lgtm
/approve

2020-10-29 21:18 UTC, merged