:book: Simplify getting-started.md and remove broken links
kubernetes-sigs/cluster-api-provider-azure pull request #1065
Opened 2020-12-03 22:13 UTC by CecileRobertMichon

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**: The cluster API quickstart points to this getting-started doc for setting up the Azure service principal. This removes all extra information that might confuse first time users and refreshes the content to be clear and concise.
 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Simplify getting-started.md and remove broken links
```

2020-12-03 22:13 UTC, CecileRobertMichon commented
/cc @craiglpeters

2020-12-03 22:17 UTC, CecileRobertMichon commented
/assign @mboersma

2020-12-03 22:34 UTC, mboersma requested changes
Looks great, just had one little grammar consistency nit to pick.

2020-12-03 22:34 UTC, mboersma commented on docs/getting-started.md
> +  NOTE: the "owner" role is required to be able to create role assignments for [system assigned managed identity](book/src/topics/identity.md).
```suggestion
  NOTE: the "owner" role is required to be able to create role assignments for [system-assigned managed identity](book/src/topics/identity.md).
```

2020-12-04 00:45 UTC, mboersma approved these changes
lgtm

2020-12-04 13:40 UTC, devigned approved these changes
/lgtm
/approve

2020-12-04 13:42 UTC, merged