Change Azure Directory -> Cloud. ALso changing Azure.Service type to …
kubernetes-sigs/cluster-api-provider-azure pull request #1094
Opened 2020-12-22 09:58 UTC by surajrana93

…Azure.Reconciler

 

 
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Clean up misnamed directory and Interace. Cleans up the code organization.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1075 

**Special notes for your reviewer**:

**TODOs**:

- [ x] squashed commits
- [x ] includes documentation

**Release note**:

```release-note
NONE
```

2020-12-22 12:56 UTC, devigned commented
/ok-to-test

Awesome! I'm super excited to see this refactor taking shape.

2020-12-22 20:10 UTC, shysank commented
@surajrana93 Thanks for the PR! The tests are failing because the generated files are out of date, and a few linter errors. Try running `make generate` to generate the latest files, and `make lint` to see the the lint errors.

2021-01-04 16:45 UTC, CecileRobertMichon commented
@surajrana93 thanks for the PR. When you get a chance, please rebase to fix the conflicts and sign the CNCF CLA so we can merge it.

2021-01-27 20:15 UTC, devigned commented
Hi @surajrana93, just a gentle nudge. Are you interested in continuing this PR? If not, we are happy to help.

2021-01-29 13:42 UTC, surajrana93 commented
@devigned 
Hi David. Extremely sorry for the delay on this. I have rebased and got the Make Lint running on this change. I'll follow up on the other requirements as well.

Again I apologize for holding this up

2021-01-29 13:43 UTC, surajrana93 commented
I signed it

2021-01-29 13:45 UTC, devigned commented
@surajrana93 no worries. We are grateful for your PR. Thank you for caring and wanting to make the community better through contribution!!

2021-01-29 13:55 UTC, surajrana93 commented
I signed it

2021-01-29 15:23 UTC, surajrana93 commented
/test pull-cluster-api-provider-azure-apidiff

2021-01-29 15:34 UTC, surajrana93 commented
@devigned  @shysank 
Any idea why the above 3 tests are failing

2021-01-29 16:54 UTC, devigned commented
odd... I pulled down the PR and it built fine. I'm going to kick the build again. Perhaps, 410 GONE was intermittent.

2021-01-29 16:54 UTC, devigned commented
/retest

2021-01-29 17:04 UTC, devigned requested changes
Please change https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/beb33be6f330c2e4ec09c7445f0d0c27834a58c6/.dockerignore#L6 to be `!/azure/**`

2021-01-29 18:48 UTC, CecileRobertMichon commented
@surajrana93 please squash the two commits

2021-02-01 08:22 UTC, surajrana93 commented
@CecileRobertMichon I've squashed the comments.  I suppose the last test is failing because of the directory changes? Is there something to be done to fix that

2021-02-01 17:10 UTC, CecileRobertMichon approved these changes
/lgtm
/assign @shysank @devigned

2021-02-01 18:14 UTC, shysank commented on azure/services/privatedns/client.go
> +	azure "sigs.k8s.io/cluster-api-provider-azure/azure"
nit: do we need this prefix now that we have renamed it to azure?

2021-02-01 18:16 UTC, shysank commented
/lgtm overall with just one small nit about redundant package prefix.

2021-02-01 18:27 UTC, devigned requested changes
Looks great outside of the superfluous import alias of `azure`.

2021-02-01 18:27 UTC, devigned commented on azure/scope/cluster.go
> +	azure "sigs.k8s.io/cluster-api-provider-azure/azure"
```suggestion
	"sigs.k8s.io/cluster-api-provider-azure/azure"
```

Please do this for the rest of the imports.

2021-02-02 18:21 UTC, surajrana93 commented
@devigned @CecileRobertMichon removed the redundant package prefix

2021-02-02 19:34 UTC, CecileRobertMichon commented
/lgtm
/retest

2021-02-02 20:09 UTC, devigned approved these changes
/lgtm

Great work!

2021-02-02 20:10 UTC, CecileRobertMichon commented
/approve

2021-02-02 20:42 UTC, devigned commented
One more rebase, please (i'm sorry).

2021-02-03 16:58 UTC, devigned commented
/lgtm
/approve
Pending tests

2021-02-03 17:37 UTC, CecileRobertMichon commented
/hold

@surajrana93 the commit history looks weird, there are two merge commits before the actual commit, can you please fix it so it looks clean?

@devigned @nader-ziada let's try to merge this before we merge anything else so we don't run into more conflicts (if it's ready to merge today and all tests are passing) since it's so hard to keep conflict free

2021-02-03 18:13 UTC, devigned commented
Thank for catching that @CecileRobertMichon

2021-02-03 20:00 UTC, nader-ziada commented
> /hold
> 
> @surajrana93 the commit history looks weird, there are two merge commits before the actual commit, can you please fix it so it looks clean?
> 
> @devigned @nader-ziada let's try to merge this before we merge anything else so we don't run into more conflicts (if it's ready to merge today and all tests are passing) since it's so hard to keep conflict free

yes, lets get this merged soon, I'm looking forward to rebasing the v1alpha4 PR on this change 😃

2021-02-03 22:26 UTC, CecileRobertMichon commented
I went ahead and rebased to get this in since @surajrana93 is in a different time zone

@devigned @nader-ziada I'll let you lgtm to make sure I didn't make any rebase mistakes (it was a clean rebase, no conflicts)

/hold cancel

2021-02-03 23:20 UTC, CecileRobertMichon commented
/retest

2021-02-04 00:15 UTC, devigned commented
/lgtm

2021-02-04 00:16 UTC, merged

2021-02-08 06:46 UTC, surajrana93 commented
/retest