[WIP]Add logs to e2e test
kubernetes-sigs/cluster-api-provider-azure pull request #1304
Opened 2021-04-13 14:42 UTC by mowangdk

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Added a Log() and Logf() helper in the e2e package that prints timestamped logs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1263 

**TODOs**:

- [ x ] squashed commits
- [] includes documentation
- [] adds unit tests

2021-04-14 21:08 UTC, shysank requested changes
@mowangdk Thanks for the PR. The log statements that you've added will be really useful for debugging. What would also further help is, to know how much time creating/updating the resources took (an ilb example is cited in #1263 ). It'd be great if you can include that info also in the logs.

2021-04-22 03:31 UTC, mowangdk commented
@shysank  ptal, I'm not sure this is the best way to add execution time. thx~

2021-04-22 16:41 UTC, shysank commented
> @shysank ptal, I'm not sure this is the best way to add execution time. thx~

Can we not just calculate start time inside `WaitForServiceAvailable ` instead? I don't think we are going to lose any accuracy if that's what you were aiming for in this approach. Wondering if there is some kind of aop pattern where we can just annotate the function (go generate??) that will just calculate the execution time. @devigned any thoughts?

2021-05-06 02:15 UTC, mowangdk commented
> > @shysank ptal, I'm not sure this is the best way to add execution time. thx~
> 
> Can we not just calculate start time inside `WaitForServiceAvailable ` instead? I don't think we are going to lose any accuracy if that's what you were aiming for in this approach. Wondering if there is some kind of aop pattern where we can just annotate the function (go generate??) that will just calculate the execution time. @CecileRobertMichon @devigned any thoughts?

If there is no other updates, I will add the timing to  ```WaitForXXX``` method. @shysank

2021-05-06 11:10 UTC, devigned requested changes
I agree with @shysank. I'd prefer to not overload `Log` functions with a return of time. I can see adding a timestamp by default to `Log*` funcs, but I don't like returning the time.

I'd prefer to see some `timed` func that might takes a func arg and have that do the timing. Perhaps, something like the following:
```go
func Timed(action func()) {
    //...
}
```

2021-05-18 23:54 UTC, CecileRobertMichon commented
@mowangdk can you please rebase when you get a chance?

2021-05-21 14:01 UTC, mowangdk commented
> @mowangdk can you please rebase when you get a chance?

ok~

2021-05-24 02:32 UTC, mowangdk commented
/retest

2021-05-24 16:18 UTC, shysank requested changes

2021-05-24 16:18 UTC, shysank commented on test/e2e/azure_net_pol.go
> +	Log("starting to cleaning up after ourselves")
can we be more specific about what we are cleaning up here?

2021-05-24 16:18 UTC, shysank commented on test/e2e/azure_net_pol.go
> +	Log("starting to cleaning up after ourselves")
same for other places as well.

2021-05-24 16:18 UTC, shysank commented on test/e2e/azure_net_pol.go
> +	Log("starting to applying a network policy to deny access to app: webapp, role: backend pods in development namespace")
I see that you're trying to use the test description for log statements. Would it be more useful if we can add details about the resource being applied. Eg:
`Logf("Applying network policy %s/%s", namespaceE2E, nwpolicyName)`

2021-05-24 16:18 UTC, shysank commented on test/e2e/azure_net_pol.go
> +	Log("starting to applying a network policy to deny access to app: webapp, role: backend pods in development namespace")
Same for other places as well.

2021-05-24 22:04 UTC, CecileRobertMichon commented
/release-note-none

2021-05-27 16:42 UTC, shysank commented
/test pull-cluster-api-provider-azure-e2e

2021-05-27 23:23 UTC, CecileRobertMichon commented
/lgtm
/approve

2021-05-27 23:42 UTC, shysank commented
Thanks @mowangdk for being patient with the reviews!

2021-05-28 00:14 UTC, merged

2021-05-30 05:16 UTC, mowangdk commented
> Thanks @mowangdk for being patient with the reviews!
You're welcome~ I am willing to provide more help if there is a chance