Expose cloud provider backoff config
kubernetes-sigs/cluster-api-provider-azure pull request #1415
Opened 2021-06-07 07:37 UTC by Ankitasw

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This pr allows for customization of cloud provider backoff config through AzureCluster spec.

**Which issue(s) this PR fixes**:
Fixes #1382

**TODOs**:
- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
Expose cloud provider backoff config
```

2021-06-07 15:33 UTC, shysank commented
/ok-to-test

2021-06-07 18:52 UTC, shysank reviewed
@Ankitasw Thanks for the PR! Just a couple of comments on the Backoffs data structure, otherwise looks good so far pending tests.

2021-06-07 18:52 UTC, shysank commented on api/v1alpha4/types.go
> +	BackOffs   []BackOffSpec   `json:"backOffs,omitempty"`
Do we need `BackOffSpec` here? Unlike rate limits, there is not going to be different backoff configurations. Can we directly use `BackOffConfig` here?

2021-06-07 18:52 UTC, shysank commented on controllers/helpers.go
> +	for _, backOff := range d.CloudProviderConfigOverrides().BackOffs {
We won't need this loop once the above comment is addressed.

2021-06-08 08:47 UTC, Ankitasw commented
/retest

2021-06-08 14:48 UTC, nader-ziada commented
looks good

2021-06-08 16:07 UTC, shysank commented on controllers/helpers.go
> +	CloudProviderBackoffExponent float32 `json:"cloudProviderBackoffExponent,omitempty"`
This should be `float64` to be in line with [cloud-provider-azure](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/d585c2031925b39c925624302f22f8856e29e352/pkg/provider/azure.go#L186)

2021-06-08 16:07 UTC, shysank commented on controllers/helpers.go
> +	CloudProviderBackoffJitter   float32 `json:"cloudProviderBackoffJitter,omitempty"`
Same as above => https://github.com/kubernetes-sigs/cloud-provider-azure/blob/d585c2031925b39c925624302f22f8856e29e352/pkg/provider/azure.go#L188

2021-06-08 16:09 UTC, devigned requested changes
Consider returning a struct rather than a ptr from `toCloudProviderBackOffConfig`.

2021-06-08 16:09 UTC, devigned commented on controllers/helpers.go
> +func toCloudProviderBackOffConfig(source infrav1.BackOffConfig) *BackOffConfig {
Why return a ptr here if when it is used, it is dereferenced?
```go
cpc.BackOffConfig = *toCloudProviderBackOffConfig(d.CloudProviderConfigOverrides().BackOffs)
```

2021-06-09 12:26 UTC, devigned approved these changes
lgtm

Thank you!

2021-06-09 13:50 UTC, nader-ziada commented
/lgtm
/approve

2021-06-09 13:51 UTC, merged