[WIP] aad support for aks
kubernetes-sigs/cluster-api-provider-azure pull request #1416
Opened 2021-06-07 09:41 UTC by LochanRn

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adds azure active directory support to authorise users who access the cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1407 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note

```

2021-06-07 09:44 UTC, LochanRn commented
This is just an initial commit to review changes/modifications done after changing the containerservice sdk.

2021-06-07 13:17 UTC, devigned requested changes
The update of the API version looks good. I only question the `VMSizeTypes` to `*string` change and what it means about the behavior of the `PUT` request to Azure.

The change can be seen by comparing: [API version 2021-02-01](https://github.com/Azure/azure-sdk-for-go/blob/8cce9bda0fa6d8c5418c65b2f890cb382197a18d/services/containerservice/mgmt/2021-02-01/containerservice/models.go#L1226) and [API version 2021-03-01](https://github.com/Azure/azure-sdk-for-go/blob/8cce9bda0fa6d8c5418c65b2f890cb382197a18d/services/containerservice/mgmt/2021-03-01/containerservice/models.go#L1270).

One thing to consider. Perhaps, this should be it's own PR, rather than combining this with the AAD support as the name of the PR implies, `[WIP] aad support for aks`.

2021-06-07 13:18 UTC, devigned commented
/ok-to-test

2021-06-07 14:29 UTC, alexeldeib commented on azure/services/agentpools/agentpools.go
> +			VMSize:              &agentPoolSpec.SKU,
You’d be correct :) 

https://github.com/Azure/azure-rest-api-specs/pull/13763#issuecomment-824171240

2021-06-07 14:33 UTC, devigned commented on azure/services/agentpools/agentpools.go
> +			VMSize:              &agentPoolSpec.SKU,
Thank you for the confirmation, @alexeldeib!

2021-06-07 17:45 UTC, CecileRobertMichon commented
@LochanRn please amend the commit to accurately describe what this is doing (it's not actually adding support for AAD)

2021-06-07 18:56 UTC, LochanRn commented
/test pull-cluster-api-provider-azure-e2e-windows

2021-06-07 22:34 UTC, CecileRobertMichon commented
I tried creating an aks cluster from this changeset, getting:

```
[manager] E0607 22:33:26.804946       7 controller.go:302] controller-runtime/manager/controller/azuremanagedcontrolplane "msg"="Reconciler error" "error"="error creating AzureManagedControlPlane default/aks-template: failed to reconcile managed cluster: failed to reconcile managed cluster aks-template: failed to create managed cluster, failed to begin operation: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code=\"MustDefineAtLeastOneSystemPool\" Message=\"Must define at least one system pool.\"" "name"="aks-template" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureManagedControlPlane" 
```

/hold

2021-06-14 17:49 UTC, CecileRobertMichon commented
@alexeldeib can you validate that setting the agent pool to mode System for now is appropriate to mitigate the error until #1376 is implemented?

2021-06-14 17:55 UTC, alexeldeib commented
I think we need to implement #1376 in tandem with the SDK update tbh, or else deletion behavior will get pretty messy. @LochanRn reached out on slack and sounds like will address #1376 + SDK update. I think the AAD functionality would be good in a follow up PR after that.

2021-07-08 13:06 UTC, LochanRn commented
closing this PR as it is fixed in #1475

2021-07-08 13:06 UTC, closed without merging