Add script to run shellcheck on bash scripts in the repository
kubernetes-sigs/cluster-api-provider-azure pull request #1425
Opened 2021-06-08 21:10 UTC by fristonio

* Add a bash script to run shellcheck on all the scripts in the repository. Derived from [Kubernetes Shellcheck](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-shellcheck.sh).
* Add `verify-shellcheck` make target and include it as a part of `make verify`.
* Fix shellcheck warnings in the repository. 

/kind other

Fixes #1337

```release-note
NONE
```

2021-06-09 18:40 UTC, mboersma commented
/ok-to-test

2021-06-10 14:21 UTC, mboersma commented
This is great IMHO! I think `shellcheck` is a very useful tool.

It's failing because there's no `shellcheck` binary in the test environment, so it tries to run the Docker image but fails. I assume this is because we're already in a container that doesn't allow Docker-in-Docker.

I can think of three ways around that:
- change the `verify-shellcheck.sh` script to download the binary and put it in the $PATH if it's not found (maybe only when running in a  container?)
- prime the test container that runs the `pull-cluster-api-provider-azure-verify` job with the `shellcheck` binary
- enable Docker-in-Docker for the test container

I think #2 (make sure `shellcheck` is already there) seems simplest, but I'm not actually sure where to make that change. @fristonio what do you think?

2021-06-10 14:54 UTC, devigned commented
> I think option 2 (make sure shellcheck is already there) seems simplest, but I'm not actually sure where to make that change. 

I'd vote for adding a prow job with Docker in Docker support or adding it to the exiting job. Here's an example of a PR: https://github.com/kubernetes/test-infra/commit/4fcd52d5bbed6cc3bd7451894571e2d50c1b0aa6

2021-06-10 17:01 UTC, CecileRobertMichon commented
+1 on enabling dind on https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-presubmits.yaml#L167

(can be done by adding `labels:      preset-dind-enabled: "true"`) to the job definition in test-infra. @fristonio would you like to open that PR?

2021-06-10 17:02 UTC, CecileRobertMichon commented on hack/verify-shellcheck.sh
> +# Taken from - https://github.com/kubernetes/kubernetes/blob/master/hack/verify-shellcheck.sh
thanks for giving due credit here

2021-06-15 00:33 UTC, CecileRobertMichon commented
opened https://github.com/kubernetes/test-infra/pull/22559

2021-06-15 15:38 UTC, mboersma commented
/retest

2021-06-15 15:55 UTC, mboersma commented
Enabling Docker-in-Docker did the trick, thanks @CecileRobertMichon! Now it's just failing on actual `shellcheck` linting errors.

2021-06-16 01:12 UTC, fristonio commented
Thanks, @CecileRobertMichon for opening the PR to enable dind.
Will take a look at the remaining `shellcheck` failures.

2021-06-16 15:45 UTC, mboersma approved these changes
lgtm

2021-06-16 19:42 UTC, devigned requested changes
lgtm, but please squash the commits.

2021-06-21 20:30 UTC, CecileRobertMichon commented
/lgtm
/approve
Thanks @fristonio !

2021-06-21 20:30 UTC, merged