[wip] Deflake the Windows e2e upstream tests
kubernetes-sigs/cluster-api-provider-azure pull request #1932
Opened 2021-12-16 23:49 UTC by jsturtevant

**What type of PR is this?**
/kind failing-test
/kind flake

**What this PR does / why we need it**:

The Windows upstream e2e test was randomly flaking across in CI.  I am going to use this PR to run those tests in the CI environment to get to the point of passing consistently as well as improve the general logging story for windows as I go.

The [latest update that turn off windows updates](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1881/commits/3e0a1a9d7f3c7c193851873f13c8e86a586bbb81) seems like it may have improved the tests so far.

The history of the job flaking: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-staging-containerd-windows

The job was renamed for consistency and the last couple test runs (with windows updates actually turned off) seems to be passing for the few runs we have so far: https://testgrid.k8s.io/sig-windows-master-release#capz-windows-containerd-master

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

2021-12-16 23:50 UTC, jsturtevant commented
/test ls

2021-12-16 23:50 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2021-12-17 00:05 UTC, jsturtevant commented
updated containerd to 1.6.0-beta4 and reverted the temp commit. The version has the fix for automatic updates 

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts-serial-slow

2021-12-17 16:25 UTC, jsturtevant commented
pass 1 with 1.6-beta4 and automatic updates disabled on vhd passed.

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts-serial-slow

2021-12-17 20:17 UTC, jsturtevant commented
pass 2 with 1.6-beta4 and automatic updates disabled on vhd passed.

Added additional logging of ctrd and e2e namespace dumping.

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts-serial-slow

2021-12-17 21:46 UTC, jsturtevant commented
so `pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts` had a single test fail though it looks like it passed. Went back and looked and pass 1 also had a single test failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1471632624580562944.  This "pass with failed tests" is tracked at https://github.com/kubernetes-sigs/cluster-api/issues/5123

This run we had namespace logs dump as well as the containerd logs.  Looking into it now.

2021-12-18 00:40 UTC, jsturtevant commented
The test failure `ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]` on in job https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1471937505442926592

Created: https://github.com/kubernetes/kubernetes/issues/107114

Initially thought it was https://github.com/kubernetes/kubernetes/issues/105942 but our successful runs are using apiserver with same local ip.

2021-12-18 00:42 UTC, jsturtevant commented
making note of to do:

-[ ] containerd logs are way to verbose, only run info?
-[ ] turn kubelet verbosity up to atleast v=2

Don't need to run the serial slow, those look solid so far (even in ci: https://testgrid.k8s.io/sig-windows-master-release#capz-windows-containerd-master-serial-slow and https://testgrid.k8s.io/sig-windows-master-release#capz-windows-containerd-2022-master-serial-slow)

2021-12-18 00:43 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-03 18:29 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-03 23:08 UTC, jsturtevant commented
The [previous run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1472004445293252608) failed `Kubernetes e2e suite: [sig-storage] HostPath should support r/w [NodeConformance]`


Kubelet shows context deadline exceeded:  
```
E1218 01:30:37.845909     756 remote_runtime.go:448] "StartContainer from runtime service failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded" containerID="15aebab25067e54766ebc0be9dc99c968a00b361f6ed43e57029faa04fa3777a"
E1218 01:30:37.912715     756 kuberuntime_manager.go:918] container &Container{Name:test-container-1,Image:k8s.gcr.io/e2e-test-images/agnhost:2.33,Command:[],Args:[mounttest --new_file_0644=/test-volume/test-file --file_mode=/test-volume/test-file],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:test-volume,ReadOnly:false,MountPath:/test-volume,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:kube-api-access-6mg9s,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod pod-host-path-test_hostpath-1042(af6bff34-d058-4d2a-82fa-bdaf167dd24f): RunContainerError: context deadline exceeded
```

Containerd shows it failed on starting container:

```
[1710] {"Timestamp":"2021-12-18T01:28:36.5680043+00:00","ProviderName":"ContainerD","Level":4,"Keywords":0,"Payload":{"ID":1,"EventName":"LogrusEntry","TraceEventProcessID":2568,"TraceEventProcessName":"","Message":"CreateContainer within sandbox \"3c0e51d2dcd492d86b4b5f6ebfdef85525a5547870985d81f5ea0c51504c9ab0\" for container &ContainerMetadata{Name:test-container-1,Attempt:0,}","Time":"2021-12-18T01:28:36.6895229+00:00"}}

[1711] {"Timestamp":"2021-12-18T01:28:37.6602139+00:00","ProviderName":"ContainerD","Level":4,"Keywords":0,"Payload":{"ID":1,"EventName":"LogrusEntry","TraceEventProcessID":2568,"TraceEventProcessName":"","Message":"CreateContainer within sandbox \"3c0e51d2dcd492d86b4b5f6ebfdef85525a5547870985d81f5ea0c51504c9ab0\" for &ContainerMetadata{Name:test-container-1,Attempt:0,} returns container id \"15aebab25067e54766ebc0be9dc99c968a00b361f6ed43e57029faa04fa3777a\"","Time":"2021-12-18T01:28:37.7821839+00:00"}}

[1877] {
  "Timestamp": "2021-12-18T01:30:43.946307+00:00",
  "ProviderName": "Microsoft.Virtualization.RunHCS",
  "Level": 2,
  "Keywords": 0,
  "Payload": {
    "ID": 42,
    "EventName": "LogrusEntry",
    "TraceEventProcessID": 6732,
    "TraceEventProcessName": "",
    "Message": "Span",
    "Time": "2021-12-18T01:30:44.0729935+00:00",
    "configuration": "{\"Owner\":\"containerd-shim-runhcs-v1.exe\",\"SchemaVersion\":{\"Major\":2,\"Minor\":1},\"Container\":{\"GuestOs\":{\"HostName\":\"pod-host-path-test\"},\"Storage\":{\"Layers\":[{\"Id\":\"aeda17e4-7a45-57a2-892a-038f3e82b29d\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\64\"},{\"Id\":\"28951435-cf40-5213-82ba-d8961b5e6f01\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\63\"},{\"Id\":\"83621030-7522-570b-ab7c-cf9c5898f09c\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\62\"},{\"Id\":\"919895fb-68c2-59f7-81ef-70644e60edbb\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\61\"},{\"Id\":\"19938ad8-e9f7-562b-8692-a78218a5c19e\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\60\"},{\"Id\":\"4762a900-545b-5612-a742-1de667da2e65\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\59\"},{\"Id\":\"d6238823-711c-54fc-b904-bba353df3f5d\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\58\"},{\"Id\":\"39ba93d7-37c8-5784-936c-83a48a4eb8bf\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\57\"},{\"Id\":\"5e7bf9b6-9d9a-5f72-adf4-08bfe724944c\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\56\"},{\"Id\":\"14d2a5ba-a271-55d7-bc34-6e49006c4049\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\55\"},{\"Id\":\"10d35d08-370c-56da-8a35-46e297b38ffc\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\54\"},{\"Id\":\"dcb2bcd5-cde9-5bf1-81ec-6b93264ba02c\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\53\"},{\"Id\":\"d7d84357-28fe-5df2-8f6a-2985555b9948\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\52\"},{\"Id\":\"0d2697ba-ba39-5414-948c-ad5b2a226283\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\51\"},{\"Id\":\"082b4cb4-4fbe-5897-9108-a61cb59ce8af\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\50\"},{\"Id\":\"bbbb1195-5432-574e-8739-8127020ad0fe\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\49\"},{\"Id\":\"d38ba07a-e3bc-5bd8-84c3-95e5ce57a0a6\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\48\"},{\"Id\":\"0c2cc0ea-efc8-5f70-9a24-f6c84ceeb007\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\47\"},{\"Id\":\"718b2916-1477-5c78-937a-adf97fec3195\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\46\"},{\"Id\":\"6f7cd04b-fdd7-5a41-98d4-7c81645311d5\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\45\"},{\"Id\":\"77ff2cbc-0b4c-5fec-a05b-25c23358031f\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\44\"},{\"Id\":\"f866332f-8f20-5642-93f6-ca3401a30f98\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\43\"},{\"Id\":\"6d08839d-52eb-508f-9338-8c90aee603f3\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\42\"},{\"Id\":\"72acf0d2-9a33-5e03-b759-c5255b23480c\",\"Path\":\"C:\\\\ProgramData\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\5\"}],\"Path\":\"\\\\\\\\?\\\\Volume{223042f1-5fa1-11ec-a648-fa7ed71c91c3}\\\\\"},\"MappedDirectories\":[{\"HostPath\":\"\\\\\\\\?\\\\Volume{1467b57a-0000-0000-0000-501f00000000}\\\\tmp\",\"ContainerPath\":\"c:\\\\test-volume\"},{\"HostPath\":\"\\\\\\\\?\\\\Volume{1467b57a-0000-0000-0000-501f00000000}\\\\var\\\\lib\\\\kubelet\\\\pods\\\\af6bff34-d058-4d2a-82fa-bdaf167dd24f\\\\containers\\\\test-container-1\\\\6e94777c\",\"ContainerPath\":\"c:\\\\dev\\\\termination-log\"},{\"HostPath\":\"\\\\\\\\?\\\\Volume{1467b57a-0000-0000-0000-501f00000000}\\\\var\\\\lib\\\\kubelet\\\\pods\\\\af6bff34-d058-4d2a-82fa-bdaf167dd24f\\\\volumes\\\\kubernetes.io~projected\\\\kube-api-access-6mg9s\",\"ContainerPath\":\"c:\\\\var\\\\run\\\\secrets\\\\kubernetes.io\\\\serviceaccount\",\"ReadOnly\":true},{\"HostPath\":\"\\\\\\\\?\\\\Volume{1467b57a-0000-0000-0000-501f00000000}\\\\var\\\\lib\\\\kubelet\\\\pods\\\\af6bff34-d058-4d2a-82fa-bdaf167dd24f\\\\etc-hosts\",\"ContainerPath\" [...]

2022-01-04 01:38 UTC, jsturtevant commented
` [sig-network] Services should serve multiport endpoints from pods [Conformance]` failed in run: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1478071052172005376. I didn't see anything obvious with the failure. Calico and kubeproxy both had the network configured properly from what i could see with logs.

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-04 16:29 UTC, jsturtevant commented
in the [last run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1478179060814188544) there were three failures

- `[sig-network] Proxy version v1 A set of valid responses are returned for both pod and service Proxy [Conformance]`
  - pod stayed in pending and wasn't marked for starting till 1:54 when the ns had already been deleted: `I0104 01:54:09.969560    4568 fake_cpu_manager.go:51] "AddContainer" pod="proxy-1796/agnhost" containerName="agnhost" containerID="f7820f185130ef8088747197880e4aae29fe095fce763791c5a87b3938490d5a"`
  - `E0104 01:54:09.981617    4568 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"agnhost.16c6ee693c118c28", GenerateName:"", Namespace:"proxy-1796", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"proxy-1796", Name:"agnhost", UID:"56ed894d-a0ee-48fe-af36-be28d38dbcc8", APIVersion:"v1", ResourceVersion:"2237", FieldPath:"spec.containers{agnhost}"}, Reason:"Created", Message:"Created container agnhost", Source:v1.EventSource{Component:"kubelet", Host:"capz-conf-swjch"}, FirstTimestamp:time.Date(2022, time.January, 4, 1, 54, 9, 969884200, time.Local), LastTimestamp:time.Date(2022, time.January, 4, 1, 54, 9, 969884200, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "agnhost.16c6ee693c118c28" is forbidden: unable to create new content in namespace proxy-1796 because it is being terminated' (will not retry!)`


- ` [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should perform canary updates and phased rolling updates of template modifications [Conformance]`
  - this was running at the same time as `Garbage collector should orphan pods created by rc if delete options say so` which is similiar reason for failure above

- `[sig-windows] Services should be able to create a functioning NodePort service for Windows `
  - this is tracked in https://github.com/kubernetes/kubernetes/issues/98499

2022-01-04 17:37 UTC, jsturtevant commented
Some of the errors seeing here are mentioned in https://github.com/kubernetes/kubernetes/issues/107290

2022-01-04 20:06 UTC, jsturtevant commented
Reduced containerd logs, increased verbosity in kubelet and don't collect duplicate logs (until https://github.com/kubernetes-sigs/image-builder/pull/762 merges)

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-04 20:41 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-04 23:25 UTC, jsturtevant commented
Failure in [last run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1478466535319146496) was:

- `[sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should perform canary updates and phased rolling updates of template modifications [Conformance] expand_more`

the pod never became ready to readiness prob failing, it initially failed with context deadline execeed, then was getting a 404.  This looks similiar to https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1932#issuecomment-1004467840.  The 404 tells me that that the container did get started and network was set up properly but something in the container wasn't running?

```
I0104 21:27:01.289309    4700 prober.go:121] "Probe failed" probeType="Readiness" pod="statefulset-4142/ss2-2" podUID=eeb9858f-2e3e-4df1-9750-f67a3546fb08 containerName="webserver" probeResult=failure output="Get \"http://192.168.241.167:80/index.html\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
I0104 21:27:01.290362    4700 kubelet.go:2161] "SyncLoop (probe)" probe="readiness" status="" pod="statefulset-4142/ss2-2"
I0104 21:27:01.302988    4700 prober.go:121] "Probe failed" probeType="Readiness" pod="statefulset-4142/ss2-2" podUID=eeb9858f-2e3e-4df1-9750-f67a3546fb08 containerName="webserver" probeResult=failure output="HTTP probe failed with statuscode: 404"
```

Going to collect the cni executabe logs for each node as well.

As for the other updates, The containerd logs were reduced dramatically and kubelet logs are at verbosity 2 as well as reduced duplication.

2022-01-04 23:39 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-05 00:58 UTC, jsturtevant commented
[latest run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1478511324873887744):

- `[It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]`
  - this failed same as above https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1932#issuecomment-997108753

- [sig-windows] Services should be able to create a functioning NodePort service for Windows
  -  this is tracked in [#98499](https://github.com/kubernetes/kubernetes/issues/98499) and was seen above https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1932#issuecomment-1004956074

2022-01-05 01:07 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-05 01:18 UTC, jsturtevant commented
> One thing to note here is this test was running during the time that the `Garbage collector should orphan pods created by rc if delete options` test was running and see similiar behavior of the pods on that test that are getting created way late in the process after the Namespace for that test was deleted:

on a local cluster I confirmed this same behavior for this test.  The test completes, but the containers are still being created on Windows side for awhile after, once they come up running kubelet tells them to go away. All this churn causes high cpu.  There maybe be better ways to handle this for windows since the container creation and deletion are expensive operations especially with so many containers all at once.

2022-01-05 02:34 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-05 19:02 UTC, jsturtevant commented
Ran two different run since last update, it doesn't seem that defender makes a huge difference as I saw failures in both.  There might be some optimizations but didn't resolve completely.  

Run [1478533581516050432](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1478533581516050432) failed with:

`Projected downwardAPI [It] should provide container's cpu request [NodeConformance] [Conformance]`

```
Jan  5 01:58:20.267: INFO: At 2022-01-05 01:57:16 +0000 UTC - event for downwardapi-volume-eaa013bf-9281-47b4-b9ea-67ca46f6431f: {kubelet capz-conf-w8lfd} FailedCreatePodSandBox: Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Jan  5 01:58:20.267: INFO: At 2022-01-05 01:57:17 +0000 UTC - event for downwardapi-volume-eaa013bf-9281-47b4-b9ea-67ca46f6431f: {kubelet capz-conf-w8lfd} FailedCreatePodSandBox: Failed to create pod sandbox: rpc error: code = Unknown desc = failed to reserve sandbox name "downwardapi-volume-eaa013bf-9281-47b4-b9ea-67ca46f6431f_projected-6978_99fa79d8-d5ba-4066-b7b7-da440939a60f_0": name "downwardapi-volume-eaa013bf-9281-47b4-b9ea-67ca46f6431f_projected-6978_99fa79d8-d5ba-4066-b7b7-da440939a60f_0" is reserved for 
```

Containerd failed to start the container:

```
{"Timestamp":"2022-01-05T01:57:17.023552+00:00","ProviderName":"Microsoft.Virtualization.RunHCS","Level":2,"Keywords":0,"Payload":{"ID":34,"EventName":"LogrusEntry","TraceEventProcessID":8976,"TraceEventProcessName":"","Message":"Span","Time":"2022-01-05T01:53:30.8030471+00:00","duration":"3m46.2341222s","eid":"","endTime":"2022-01-05T01:57:17.0371693+00:00","name":"Start","parentSpanID":"826370b7613107c5","podid":"f9b676f74a5df779e432e7dabe41bdc8e466cd52d5037d67b3acb4fd85e45163","spanID":"b9192a621014d004","startTime":"2022-01-05T01:53:30.8030471+00:00","tid":"f9b676f74a5df779e432e7dabe41bdc8e466cd52d5037d67b3acb4fd85e45163","traceID":"aff0bb1af2610eeff1d4a22705b10725","error":"hcs::System::Start f9b676f74a5df779e432e7dabe41bdc8e466cd52d5037d67b3acb4fd85e45163: context deadline exceeded"}}
```

The previous run didn't happen during `Garbage collector should orphan pods created by rc if delete options` but there was another test similiar that left a 50 pods being deleted during the run of the test. This is similiar behavior where the GC tests exit but containers are still starting and deleting causing havoc on the later tests:

```
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
Jan  5 01:52:50.327: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
[1mSTEP[0m: Destroying namespace "gc-2799" for this suite.
{"msg":"PASSED [sig-api-machinery] Garbage collector should not delete dependents that have both valid owner and owner that's waiting for dependents to be deleted [Conformance]"
````

2022-01-05 19:16 UTC, jsturtevant commented
for run [1478555584801280000](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1478555584801280000) it looks like networking was set up properly.  I see a few interesting logs that lead me to think something went wrong but I am not as familiar with the code here.  Running the test continuously by it's self I haven't had any failures so must be related to other tests running when it was running. I will have to circle back to this to get more details but I think increasing the kube-proxy verbosity will be useful.

`https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1478555584801280000`:

```
Jan  5 03:02:48.881: INFO: Service reachability failing with error: error running /usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig --namespace=services-4875 exec execpodllf6d -- /bin/sh -x -c echo hostName | nc -v -t -w 2 multi-endpoint-test 80:
Command stdout:

stderr:
+ echo hostName
+ nc -v -t -w 2 multi-endpoint-test 80
multi-endpoint-test.services-4875.svc.cluster.local [10.108.165.148] 80 (http): TIMEDOUT      
command terminated with exit code 1
```

kubeproxy logs that are suspicious:

```
I0105 03:01:31.738314    4440 service.go:304] "Service updated ports" service="services-4875/multi-endpoint-test" portCount=2
I0105 03:01:31.738995    4440 service.go:419] "Adding new service port" portName="services-4875/multi-endpoint-test:portname1" servicePort="10.108.165.148:80/TCP"
I0105 03:01:31.739532    4440 service.go:419] "Adding new service port" portName="services-4875/multi-endpoint-test:portname2" servicePort="10.108.165.148:81/TCP"
E0105 03:01:31.761451    4440 proxier.go:1202] "Endpoint information not available for service, not applying any policy" serviceName="services-4875/multi-endpoint-test:portname1"
E0105 03:01:31.766656    4440 proxier.go:1202] "Endpoint information not available for service, not applying any policy" serviceName="services-4875/multi-endpoint-test:portname2"
E0105 03:01:31.776790    4440 proxier.go:1202] "Endpoint information not available for service, not applying any policy" serviceName="services-4875/multi-endpoint-test:portname1"
E0105 03:01:31.781184    4440 proxier.go:1202] "Endpoint information not available for service, not applying any policy" serviceName="services-4875/multi-endpoint-test:portname2"
E0105 03:01:43.099561    4440 proxier.go:1202] "Endpoint information not available for service, not applying any policy" serviceName="services-4875/multi-endpoint-test:portname2"
```

2022-01-05 20:39 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-05 21:43 UTC, jsturtevant commented
got the first green test pass with the GC tests disabled! 

`Test started today at 12:39 PM passed after 59m36s. (more info)`

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-06 00:45 UTC, jsturtevant commented
unfortunately that [latest run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1478844611844640768) didn't pass, there were several errors (some of them repeats) but the one that stands out which has happened previously:

```
Jan  5 22:36:16.656: INFO: At 2022-01-05 22:35:18 +0000 UTC - event for pod2: {kubelet capz-conf-l8wfg} FailedCreatePodSandBox: Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Jan  5 22:36:16.657: INFO: At 2022-01-05 22:35:19 +0000 UTC - event for pod2: {kubelet capz-conf-l8wfg} FailedCreatePodSandBox: Failed to create pod sandbox: rpc error: code = Unknown desc = failed to reserve sandbox name "pod2_services-712_d2aecc52-64d4-4901-a839-c2202405297f_0": name "pod2_services-712_d2aecc52-64d4-4901-a839-c2202405297f_0" is reserved for "815a9c0a23d13807d237274ef0de4c0832e682cd1c9f7d7627d9b4ba3c047f0d"
```

2022-01-06 00:45 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-06 01:55 UTC, jsturtevant commented
Test pass, now 2/3 which is improvement 

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-06 03:02 UTC, jsturtevant commented
Test pass, now 3/4

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-06 04:11 UTC, jsturtevant commented
Test pass, now 4/5

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-06 05:18 UTC, jsturtevant commented
Test pass, now 5/6

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-06 17:12 UTC, jsturtevant commented
6/7 passed, the one failure looks like it was containerd related and there are a few fixes coming soon with the next 1.6 release which may help. But over all removing the GC collection tests did help.  

To summarize this long thread, it seems there are a few things happening:
  - `Garbage collector should orphan pods created by rc if delete options say so` or other similiar GC tests create 30-40+ pods on the VM's.  The tests checks that the pods don't get GC'd then delete them with `termination-graceperiod=0`  and the test completes.  This leaves all of those pods in `ContainerCreating` state until a much later point when the containers are started and then issued an immediate delete. All of this causes strain (high cpu) on the system and other pods end up timing out or other issues.  Note this is really only an issue on Windows due to the overhead of starting/deleting containers.  These containers can take 10+ mins to clear from the system causing other tests run after to timeout.
    - Action: investigate if there are locks or other system things that could be improved to help the system.  Also move these tests to serial/slow job to alleviate flakes temporarily.
  - There are some networking flakes that showed up during the tests runs which seems to be related to networking not being set up properly.  At least once this occurred right after the above GC tests issue and could cause timing delays in the nework configuration.
    - Action: continue to monitor for these flakes in CI and investigate if see further.
  -  `failed to reserve sandbox name "downwardapi-volume-eaa013bf-9281-47b4-b9ea-67ca46f6431f_projected-6978_99fa79d8-d5ba-4066-b7b7-da440939a60f_0":`  This error showed up several times and maybe due to either timeouts or some other recent fixes that went into hcsshim ( https://github.com/microsoft/hcsshim/pull/1249, https://github.com/microsoft/hcsshim/pull/1252, https://github.com/microsoft/hcsshim/pull/1252)
     - Action: continue to monitor for these flakes in CI and investigate if see further after using latest containerd fixes

Improvements in this PR are mostly related to logging and base line stability (see commits)
  - use latest containerd 1.6.4 beta for tests
  - remove temp auto update disabled.  auto updates are turned of in base image
  - Dump namespace logs on test failure for windows
  - enable logging for containerd on windows
  - Update kubelet logs to v2 and de-dup the output
  - Add cni executable log
  - Set Kubelet process Priority to above normal 

Proposed next steps:
  - Merge this PR so CI can get these fixes and we can do better investigations that we currently can with CI
  - Create another PR that moves the GC tests to serial runs while investigation into root cause of those tests.  This allows us to have a cleaner signal in CI and revert once we resolve the underlying issues with GC tests (k/k issue: tbd)
  - Create a nightly containerd run with (similiar to our aks-e run which allows us test the latest fixes coming in. (https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1859)

2022-01-10 18:10 UTC, jsturtevant commented
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts
/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts-serial-slow

2022-01-10 19:14 UTC, jsturtevant commented
The failure was https://github.com/kubernetes/kubernetes/issues/107114.  I would like to get this in to help with CI and will look into this in the in parallel.

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

2022-01-10 21:38 UTC, jsturtevant commented
The failure on the slow job was a timeout because of the moving of the GC jobs.  The container started successfully but after the test had timed out.  This move has been running in [CI successfully so far](https://testgrid.k8s.io/sig-windows-master-release#capz-windows-containerd-master-serial-slow), so I am hopeful this flake is rare and will be handled once https://github.com/kubernetes/kubernetes/issues/107394 if fully resolved.

```
I0110 20:00:04.499861     916 kubelet.go:2082] "SyncLoop (PLEG): event for pod" pod="sched-preemption-path-5423/without-label" event=&{ID:2b103a3a-c922-4870-80fc-386290b0c482 Type:ContainerStarted Data:7fb32fddf184e5981b1ed9324951f20cd83097d62765a0b2668633207be5028d}
```

GC test running right before:

```
Jan 10 19:56:26.969: INFO: Deleting pod "simpletest.rc-zwzcq" in namespace "gc-7870"
[AfterEach] [sig-api-machinery] Garbage collector
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
Jan 10 19:56:26.990: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
[1mSTEP[0m: Destroying namespace "gc-7870" for this suite.
[32m•[0m{"msg":"PASSED [sig-api-machinery] Garbage collector should orphan pods created by rc if delete options say so 
```

/test pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts-serial-slow

2022-01-11 00:52 UTC, jsturtevant commented
/assign @CecileRobertMichon @devigned

2022-01-11 14:41 UTC, devigned requested changes
Love all the logging improvements. Thank you, @jsturtevant.

What do you think about squashing these commits?

Besides that, lgtm.

2022-01-11 17:00 UTC, jsturtevant commented
> What do you think about squashing these commits?

Each of the commits is a separate piece of functionality that all improve the experience together.   They could each be small PR's but I think they are better grouped together here.  IMO it will be easier to grok the changes individually in the future when looking at the commit history if they are separate commits.

2022-01-11 19:38 UTC, CecileRobertMichon commented
/test ls

2022-01-11 19:39 UTC, CecileRobertMichon commented
/test pull-cluster-api-provider-azure-capi-e2e
/test pull-cluster-api-provider-azure-conformance
/test pull-cluster-api-provider-azure-conformance-with-ci-artifacts

Just to be cautious since we're touching test templates...

/lgtm

2022-01-12 00:11 UTC, jsturtevant commented
hmm, the capi-e2e test passed all the tests but it timed out:

```
{"component":"entrypoint","file":"prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15m0s grace period","severity":"error","time":"2022-01-11T23:55:46Z"}
{"component":"entrypoint","error":"os: process already finished","file":"prow/entrypoint/run.go:257","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Could not kill process after grace period","severity":"error","time":"2022-01-11T23:55:46Z"}
```

Seems like there may have been some trouble with the activity logs:
```
[1mSTEP[0m: Got error while iterating over activity logs for resource group capz-e2e-cs4pov: insights.ActivityLogsClient#listNextResults: Failure preparing next results request: StatusCode=0 -- Original Error: invalid semicolon separator in query
```

and collecting system logs looks like it wasn't working:

```
[1mSTEP[0m: Got error while streaming logs for pod kube-system/calico-node-windows-fbg2n, container calico-node-startup: http2: client connection lost
[1mSTEP[0m: Got error while streaming logs for pod kube-system/kube-controller-manager-md-scale-v6c5eo-control-plane-gpdhl, container kube-controller-manager: http2: client connection lost
[1mSTEP[0m: Got error while streaming logs for pod kube-system/kube-scheduler-md-scale-v6c5eo-control-plane-gpdhl, container kube-scheduler: http2: client connection lost
[1mSTEP[0m: Got error while streaming logs for pod kube-system/coredns-78fcd69978-hg9t8, container coredns: http2: client connection lost
[1mSTEP[0m: Got error while streaming logs for pod kube-system/calico-node-windows-5vntn, container calico-node-startup: http2: client connection lost
```

I will look a little closer but I don't think anything in this pr changed anything related to this log collection

/test pull-cluster-api-provider-azure-capi-e2e

2022-01-12 00:30 UTC, CecileRobertMichon commented
/approve

2022-01-12 01:43 UTC, merged