WIP: Overhaul Quickstart UX using AzureASOManagedCluster
kubernetes-sigs/cluster-api-provider-azure pull request #5319
Opened 2024-12-03 23:26 UTC by willie-yao

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR rewrites the quickstart to use CAPI Operator to provision a CAPZ management cluster, and to use a helm chart to deploy an AzureASOManagedCluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4866

**Special notes for your reviewer**:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] cherry-pick candidate

**Release note**:

```release-note
Overhaul Quickstart UX using AzureASOManagedCluster
```

2024-12-04 18:38 UTC, dtzar commented on docs/book/src/getting-started.md
> +```yaml
I'd say to specify here ONLY the minimum values required to provision a cluster and use the default values file provided with the chart.

2024-12-04 18:39 UTC, dtzar commented on docs/book/src/getting-started.md
> -If you are looking to install additional ASO CRDs, set `ADDITIONAL_ASO_CRDS` to the list of CRDs you want to install. Refer to adding additional CRDs for Azure Service Operator [here](./topics/aso.md
Let's keep this and include it in the CAPI-Operator install values file.

2024-12-04 20:52 UTC, dtzar commented on docs/book/src/getting-started.md
> +For more information on the `azure-aks-aso` helm chart, see the [chart documentation](https://github.com/mboersma/cluster-api-charts/tree/main/charts/azure-aks-aso#azure-aks-aso-chart).
You can remove the `clusterctl` comments since we don't even use this in these steps.

2024-12-04 20:53 UTC, dtzar commented on docs/book/src/getting-started.md
> +The recommended way to build a cluster is to install a CAPZ management cluster using [Cluster API Operator](https://github.com/kubernetes-sigs/cluster-api-operator), then utilizing a helm chart to cr
Need to add in pre-requisites that people have `az` and `helm` installed.

2024-12-04 21:00 UTC, dtzar commented on docs/book/src/getting-started.md
> -Check out the [Cluster API Quick Start](https://cluster-api.sigs.k8s.io/user/quick-start.html) to create your first Kubernetes cluster on Azure using Cluster API. Make sure to select the "Azure" tabs
Add in comment at top of the page something like:  "This quickstart is for provisioning a managed (AKS) cluster with the CAPI-operator and helm.  See the CAPI quickstart to provision a self-managed cluster on Azure using `clusterctl`.  The identity instructions can apply to either self-managed or managed cluster provisioning."

2024-12-04 21:04 UTC, dtzar commented
Would appreciate a blurb somewhere in the quickstart like: "To see how CAPZ can be utilized in a platform engineering environment to provision AKS clusters with GitOps practices using ArgoCD, see the AKS-platform-engineering sample repository".

2024-12-04 21:19 UTC, dtzar requested changes

2024-12-06 00:37 UTC, jackfrancis commented
/lgtm
/approve

@dtzar @mbrow137 feel free to submit any follow-ups to this

2024-12-10 16:26 UTC, mboersma commented on docs/book/src/getting-started.md
> +Specify values for the CAPZ AKS-ASO helm chart in a `values.yaml` file. For exmaple:
```suggestion
Specify values for the CAPZ AKS-ASO helm chart in a `values.yaml` file. For example:
```

This typo is what's preventing the PR from merging.

2024-12-10 16:28 UTC, mboersma commented on docs/book/src/getting-started.md
> +Add the CAPI Operator & cert manager helm repository, which we will use to install the management cluster.
```suggestion
Add the CAPI Operator and cert-manager helm repositories, which we will use to install the management cluster.
```

2024-12-10 16:31 UTC, mboersma commented on docs/book/src/getting-started.md
> +For more information on the `azure-aks-aso` helm chart, see the [chart documentation](https://github.com/mboersma/cluster-api-charts/tree/main/charts/azure-aks-aso#azure-aks-aso-chart).
In general, I think we should always capitalize `Helm` unless referring to the command-line tool itself. That's what they do in their [docs](https://helm.sh). But I don't want to hold up this PR just for that; just pointing it out.

2024-12-10 17:58 UTC, mboersma approved these changes
/lgtm

2024-12-10 19:34 UTC, merged