:book: fix custom image docs
kubernetes-sigs/cluster-api-provider-azure pull request #930
Opened 2020-09-13 02:24 UTC by alexeldeib

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

2020-09-13 02:35 UTC, alexeldeib commented
fixes #931

2020-09-13 23:25 UTC, alexeldeib commented
/test pull-cluster-api-provider-azure-e2e

2020-09-14 13:30 UTC, devigned requested changes

2020-09-14 13:30 UTC, devigned commented on api/v1alpha3/azuremachine_webhook.go
> +	old := oldRaw.(*AzureMachine)
nit: Can we move this statement closer to it's usage. Looks like it's not used until line 101.

2020-09-14 15:59 UTC, CecileRobertMichon commented
Nice catch

Can you please add a PR description + release note?

2020-09-14 16:25 UTC, CecileRobertMichon approved these changes
/lgtm

2020-09-14 21:10 UTC, CecileRobertMichon approved these changes
/approve

2020-09-14 21:11 UTC, merged